spring.application.name=backend-core
# Server Port
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/omniflow_db
spring.datasource.username=postgres
spring.datasource.password=9905
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Secret Key (for auth)
jwt.secret=9a6747f3b868f19da61e81279d4e7b41e32e813f895db141a22c5f8e1540f234
jwt.expiration=86400000